Add Bigfoot sighting markers to the map.
lilymzhou/stepfolio pull request #24
Opened 2020-07-09 23:37 UTC by lilymzhou

- Uploaded CSV file with bigfoot sightings data.
- Parse CSV file and convert to JSON in BigfootServlet.java.
- Add markers corresponding to sighting coordinates onto the map.
- Add clickable info windows to markers containing date of sighting, location (in words), and description.

![Screenshot 2020-07-09 at 4 30 47 PM](https://user-images.githubusercontent.com/43889831/87100909-6812b100-c202-11ea-9d6f-248bc09efc73.png)

2020-07-14 01:05 UTC, tjgoog requested changes

2020-07-14 01:05 UTC, tjgoog commented on portfolio/src/main/java/com/google/sps/data/Bigfoot.java
> +public class Bigfoot {
Could you add a javadoc here to say what instances of the class will represent?

2020-07-14 01:05 UTC, tjgoog commented on portfolio/src/main/webapp/map-script.js
> +          '<p><b>Title:</b> ' + sighting.title + '</p>' +
Even though these text fields are not directly controlled by the user of this page, it's still good practice to sanitize them to avoid XSS, since some XSS could theoretically slip into the input data.

I've been looking for some sort of browser built in function for sanitizing input, but it seems there isn't really one. You can check out Stack Overflow for ideas, or here's my idea that you could put into a function:

```
let element = document.createElement('span'); // Element type could be anything that contains text, e.g. div or b.
element.innerText = unsafeContent;
safeContent = element.innerHtml;
```

2020-07-14 17:20 UTC, lilymzhou commented on portfolio/src/main/webapp/map-script.js
> +          '<p><b>Title:</b> ' + sighting.title + '</p>' +
I just tried this, and it seems like the text isn't showing up when I run this. Changing `element.innerText = unsafeContent;` to `element.innerHtml = unsafeContent` does allow the text to be displayed, but it seems like this also leads to XSS.

2020-07-14 20:17 UTC, tjgoog requested changes

2020-07-14 20:17 UTC, tjgoog commented on portfolio/src/main/webapp/map-script.js
> +  return element.innerHtml;
```suggestion
  return element.innerHTML;
```

D'oh!

2020-07-15 00:48 UTC, tjgoog approved these changes

2020-07-15 16:38 UTC, merged